### ISSUE TITLE
Reusing golang image when use framedata image

### ISSUE THREAD

**Issue by Cacsjep** [asticode/go-astiav#36]
I'm using go-astiav to decode frames for a CCTV camera client, integrating with Fyne for the UI rendering. The renderer in this setup requires image.RGBA format from Go's standard image library. Given the scale of my application – 16 cameras at 25 frames per second – there's a significant volume of images being created in the process of decoding and use **framedata.Image()**. 

The FrameData.Image() method provided by go-astiav is quite effective, but it generates a new image instance with each invocation. 
This high throughput of image data introduces substantial workload for Go's garbage collector (GC). While this functionality is generally useful, in my context, where performance and resource efficiency are critical, it becomes less ideal. To address this, I've developed a small func that fits for my need.

Are u open for a PR for this, but i have no really deep understanding of image formats so its hard for me if you want that this should work for all image formats.
```go
func (d *FrameData) CopyIntoRgbaImage(dstImage image.RGBA) (image.RGBA, error) {
	if d.f.PixelFormat() == PixelFormatRgba {
		if d.f == nil || d.f.Width() <= 0 || d.f.Height() <= 0 {
			return dstImage, errors.New("invalid frame: either nil or has non-positive dimensions")
		}
		copy(dstImage.Pix, d.planeData(0, func(linesize int) int { return linesize * d.f.Height() }))
		dstImage.Stride = d.f.Linesize()[0]
		dstImage.Rect = image.Rect(0, 0, d.f.Width(), d.f.Height())
		return dstImage, nil
	}
	return dstImage, errors.New("invalid frame: its not an rgba frame")
}
```

btw awesome work with this lib =)

**Comment by Cacsjep** [comment]
I create a PR for just doing planeData public so devs could create functions like i did without any big change to the codebase.

**Comment by Cacsjep** [comment]
pr open

**Comment by asticode** [comment]
Actually I quite liked the idea of being able to chose between creating a new image or updating an existing one therefore I've just added a `FrameData`.`ToImage(i image.Image)` to `master`. Can you tell me whether that fixes your problem?

**Comment by Cacsjep** [comment]
cool, looks very interesting. for me i need to update a image.RGBA and not an image.NRGBA it would be greate if you could add this to ;) then it would be perfect for me =)

**Comment by asticode** [comment]
Thing is I had problems in the past using `image.RGBA` with image not being encoded or displayed properly therefore that's why I now only use `image.NRGBA`

**Comment by Cacsjep** [comment]
Strange i never had issues with rgba, would it hard to implement? I also had no issue with the function that is shown at top of this issue.

**Comment by asticode** [comment]
I think the easiest for you would be to use a `*image.NRGBA` with `astiav` but copy it to your `*image.RGBA` when needed: it only consists in copying the 3 attributes `Pix`, `Stride` and `Rect` like you presented in the comment of your PR. since `*image.NRGBA` and `*image.RGBA` have the exact same 3 fields 👍

**Comment by Cacsjep** [comment]
OK try it tomorrow and give u Feedback

**Comment by Cacsjep** [comment]
But this would require to handle two Image instances one for rgba and one for nrgba. would u be open for an PR where we just check if Image is an rgba or nrgba and handle this in the ToImage Method

**Comment by asticode** [comment]
I'll check it out tomorrow 👍

**Comment by Cacsjep** [comment]
perfect thank u

**Comment by Cacsjep** [comment]
I conducted a test where I replaced image.NRGBA with image.RGBA and found no issues with the output, even when using SMPTE color bars for color verification. Given that Libav does not have an NRGBA format and NRGBA in Go represents non-premultiplied alpha (unlike RGBA which has premultiplied alpha), it might be misleading to use NRGBA here. When users interact with NRGBA, they might expect non-premultiplied alpha, which isn’t the case with Libav's formats. Therefore, using RGBA seems more appropriate and less confusing in this context.

**Comment by asticode** [comment]
From what I've gathered from the internet, `libav` doesn't have a separate pixel format for non-premultiplied alpha rgba (or yuva) like Go does because the `libav` pixel format can contain either premultiplied or non-premultiplied values depending on the input. The only valid occurence of the `premultiplied`word I've found in ffmpeg's code is [here](https://github.com/FFmpeg/FFmpeg/blob/8c99a1429a19268e91463e21fdf2f61b8a678135/libavutil/pixdesc.h#L141) stating `The alpha is always straight, never pre-multiplied` but it seems that there's no automatic way to know whether the data is premultiplied or not: only the user, which controls the input, would know. 

Therefore here's what I've done:
- remove `func (d *FrameData) Image()`
- add `func (d *FrameData) GuessImageFormat() image.Image` which tries to guess the proper `image.Image`based on the pixel format. It will always return non-premultiplied formats when dealing with alpha channels
- allow either premultiplied or non-premultiplied images in `func (d *FrameData) ToImage(image.Image) error` therefore you can provide your own image format here **if you know what you're doing**

Let me know whether that fixes your issue

**Comment by Cacsjep** [comment]
Awesome this looks exactly what I need, this should fix it. Big thanks !
