### ISSUE TITLE
Free packet buffer after pkt.FromData

### ISSUE THREAD

**Issue by Cacsjep** [asticode/go-astiav#41]
Hey

I discover an memory leak in my app using FromData in a loop to feed bytes from my socket into the packet. the packet itself is only alloc once.

The only way that i not have the leak is when i "free" the packet and do a fresh **pkt.Alloc()**

I have seen that buffer is only freed up when there its an error case, clear to me because at this point we dont know when user does not need this buffer anymore. 

Is there a solution to avoid free/realloc the packate itself, or do we need to add a function and hold a ref to the buffer to clean it up?

thanks

```go
func (p *Packet) FromData(data []byte) (err error) {
	// Create buf
	buf := (*C.uint8_t)(C.av_malloc(C.size_t(len(data))))  <---- this is only freed in error case
	if buf == nil {
		err = errors.New("astiav: allocating buffer failed")
		return
	}

	// Make sure to free buf in case of error
	defer func() {
		if err != nil {
			C.av_freep(unsafe.Pointer(&buf))
		}
	}()

	// Copy
	if len(data) > 0 {
		C.memcpy(unsafe.Pointer(buf), unsafe.Pointer(&data[0]), C.size_t(len(data)))
	}

	// From data
	err = newError(C.av_packet_from_data(p.c, buf, C.int(len(data))))
	return
}
```

**Comment by asticode** [comment]
Once `buf` is provided to `av_packet_from_data` and it returns successfully, `buf` is owned by the underlying `AVBuffer` ([doc](https://ffmpeg.org/doxygen/5.1/group__lavc__packet.html#ga7ca877e1f0ded89a27199b65e9a077dc)) therefore you shouldn't clean it manually.

What you need to do, is call `pkt.Unref()` when you're done with the data it contains. It should unreference the data and the underlying `AVBuffer` should free it properly. Therefore in your case, you should call `pkt.Unref()` instead of `pkt.Free()`.

Let me know whether that fixes your memory leak 👍

**Comment by Cacsjep** [comment]
thanks works perfectly =)

**Comment by Cacsjep** [comment]
can closed
