### ISSUE TITLE
Question: Write to a buffer instead of file

### ISSUE THREAD

**Issue by acschristoph** [asticode/go-astiav#60]
Could u tell me how it is possible to write to a buffer or similar things when using OutputFormatContext,
i want to write the output to a websocket connection?

thanks

**Comment by asticode** [comment]
Well your timing is pretty perfect since I was just adding the needed components for what you're looking for 👍 

If you use the latest `master` or `v0.14.0`, right after using `AllocOutputFormatContext` (without providing a filename), you can use `.SetPb()` on the returned `FormatContext` and provide an `IOContext` build with the new [AllocIOContext](https://github.com/asticode/go-astiav/blob/master/io_context.go#L37C6-L37C20). This new method will allow you to provide a `write`  method with the signature `func(b []byte) (n int, err error)` which will then allow you to send the provided `b` in your websocket connection.

Let me know whether that makes sense or if you face any problem since it was very recently added 👍

**Comment by Cacsjep** [comment]
Bam, cool will try tommorow and let u Know:) thx

**Comment by Cacsjep** [comment]
works ;) hell yeah thanks

**Comment by asticode** [comment]
❤️
