### ISSUE TITLE
Support for sws_scale

### ISSUE THREAD

**Issue by elwinar** [asticode/go-astiav#8]
Hello there.

I'm trying to do some image manipulation in Golang (things like generating a color palette for a video and timestamps ranges, feeding images to a tensorflow model, etc), and I found out your library while evaluating ffmpeg and linac bindings (I'm an absolute beginer with libav in general.)

Using one of your examples as base, and the conversion function snippet by chmgr here https://github.com/asticode/go-astiav/issues/4#issuecomment-1103204084, I've succeeded in putting each frame in a image.Image.

I have multiple issues with this, the first being that the images seem to have the wrong color (like some green overlay), and the second being that there are a lot more pixel formats than YUV, so my code is essentially limited unless I'm willing to implement such a function for each format.

I've been looking at other examples of how to do this (searching google for anything libav-related seem to always yield ffmpeg or avconv command lines, sic), and finally found out this from the libav-user mailing list https://ffmpeg.org/pipermail/libav-user/2015-September/008473.html.

So, I'm thinking for a first implementation of using sws_scale to convert the frame into RGB and using the result to init an image.RGB, which would have the advantage of supporting all formats, albeit at a performance cost (not necessarily and issue at first).

Does this approach seems correct to you? If so, I didn't see sws functions in your repository, would you be open to a PR implementing the binding?

**Comment by asticode** [comment]
This approach seems pretty good to me if you're aware of the performance cost. An alternative would be to use [this filter](https://ffmpeg.org/ffmpeg-filters.html#format-1) which can convert pixel format as well.

SWS are not in this repository for now indeed, and I'd be open for a PR. In your case you'd need to add 

- a `SWSContext` struct in a `sws_context.go` file
- a `NewSWSContext() *SWSContext` function
- a `func (sc *SWSContext) Scale(...)` function
- tests in a `sws_context_test.go` file

Check out [this context](https://github.com/asticode/go-astiav/blob/master/filter_context.go) so that you can match variable naming, doc and comments.

**Comment by elwinar** [comment]
What I was thinking was to convert to RGB at first, then implement more constructors for other pixel formats as needed and only use the conversion as a fallback for unsupported formats. That way, exotic formats are slower but I can implement them if needed.

I was also thinking, do you think a custom implementation of image.Image that map directly to the frame data could be pertinent? For the supported formats that would alleviate even more the performance penalty of reading from the frames.

**Comment by asticode** [comment]
> What I was thinking was to convert to RGB at first, then implement more constructors for other pixel formats as needed and only use the conversion as a fallback for unsupported formats. That way, exotic formats are slower but I can implement them if needed.

That makes total sense 👍 

> I was also thinking, do you think a custom implementation of image.Image that map directly to the frame data could be pertinent? For the supported formats that would alleviate even more the performance penalty of reading from the frames.

I think that could be quite difficult to do so, and quite tedious since you would need to create a custom implementation for all custom pixel format if I understand correctly. I don't know how much performance is important in your project, but from a maintainability standpoint, I'd convert all input images to the same pixel format (RGBA would be my choice with Golang) and then have the same treatment for all images.

**Comment by elwinar** [comment]
Performance is important but the whole node is dedicated to it, so I can parallelize like a dummy at first, and optimize after to have a bigger throughput.

I'll try for an implementation today, maybe tomorrow.

**Comment by elwinar** [comment]
I've started looking at it, and I'm starting to see issues everywhere :D .

The examples I've found use sws_getContext to initialize the SWSContext, but the documentation of [sws_getContext](https://libav.org/documentation/doxygen/master/group__libsws.html#gaf360d1a9e0e60f906f74d7d44f9abfdd) says it's deprecated. I've found [sws_alloc_context](https://libav.org/documentation/doxygen/master/group__libsws.html#gab97d02dc20945fd013ba49afb8bd1099) which seems to be more in line with what I've seen in the other parts of the API, but I'm not sure how to have the same result with it. I think that [sws_setColorspaceDetails](https://libav.org/documentation/doxygen/master/group__libsws.html#ga541bdffa8149f5f9203664f955faa040) is supposed to be what I want, but I'm lost in the options (I've not yet searched for examples using it tho).

I'll try to finish the binding for the deprecated function and see from there if there is a "saner alternative" as the doc suggest, unless you think it's better the other way around.

**Comment by asticode** [comment]
Check out the implementation of `sws_getContext` [here](https://github.com/FFmpeg/FFmpeg/blob/2d368392a5d6b856d63959ae8bfd40dd598c27e7/libswscale/utils.c#L2069) and `sws_alloc_set_opts` [here](https://github.com/FFmpeg/FFmpeg/blob/2d368392a5d6b856d63959ae8bfd40dd598c27e7/libswscale/utils.c#L2044).

I'd rather you implement :

- sws_alloc_context
- sws_init_context
- sws_freeContext
- and all context setters + getters as listed in `sws_alloc_set_opts`

**Comment by elwinar** [comment]
OK, will do. For the Scale function itself, most of it's parameters are Frame attributes (either the source or the destination one.) Do you prefer to take the parameters as in the original function or should I just pass two frames?

**Comment by elwinar** [comment]
So. I've had a few hours at this, and came up with [this commit](https://github.com/elwinar/go-astiav/commit/c7e32e74c9785f9bbbd2883d6a3e8a8f4aa08bea) mainly to get to grips with CGo itself, which I've never used before.

I've stumbled on a few issues that I don't know what to do about, the main being that CGo doesn't seem to find the SwsContext fields. With the commit linked above, and the following snippet:

```
  package main

  import "github.com/asticode/go-astiav"

  func main() {
    var swsContext = astiav.AllocSWSContext()
    swsContext.SetSrcFormat(f.PixelFormat())
    swsContext.SetSrcH(f.Height())
    swsContext.SetSrcW(f.Width())
    swsContext.SetDstFormat(dst.PixelFormat())
    swsContext.SetDstH(dst.Height())
    swsContext.SetDstW(dst.Width())
    swsContext.Free()
  }
```

I'm getting some weird error:
```
~/d/v/ff $ make bin/thumber
go build -o bin/thumber ./thumber
# github.com/asticode/go-astiav
astiav/sws_context.go:27:18: sc.c.srcW undefined (type *_Ctype_struct_SwsContext has no field or method srcW)
astiav/sws_context.go:31:7: sc.c.srcW undefined (type *_Ctype_struct_SwsContext has no field or method srcW)
astiav/sws_context.go:35:18: sc.c.srcH undefined (type *_Ctype_struct_SwsContext has no field or method srcH)
astiav/sws_context.go:39:7: sc.c.srcH undefined (type *_Ctype_struct_SwsContext has no field or method srcH)
astiav/sws_context.go:43:26: sc.c.srcFormat undefined (type *_Ctype_struct_SwsContext has no field or method srcFormat)
astiav/sws_context.go:47:7: sc.c.srcFormat undefined (type *_Ctype_struct_SwsContext has no field or method srcFormat)
astiav/sws_context.go:51:18: sc.c.dstW undefined (type *_Ctype_struct_SwsContext has no field or method dstW)
astiav/sws_context.go:55:7: sc.c.dstW undefined (type *_Ctype_struct_SwsContext has no field or method dstW)
astiav/sws_context.go:59:18: sc.c.dstH undefined (type *_Ctype_struct_SwsContext has no field or method dstH)
astiav/sws_context.go:63:7: sc.c.dstH undefined (type *_Ctype_struct_SwsContext has no field or method dstH)
astiav/sws_context.go:63:7: too many errors
make: *** [Makefile:3: bin/thumber] Error 2
```

The only reason I've found out for this is that the struct declared [here](https://github.com/FFmpeg/FFmpeg/blob/n4.2.7/libswscale/swscale_internal.h#L280) is somehow misaligned. I don't see _pragma packed_ anywhere near the said struct and I don't think you can misalign a struct without this or compiler parameters.

Do you have any idea about this?

**Comment by asticode** [comment]
Here's what I think : [what you've linked](https://github.com/FFmpeg/FFmpeg/blob/n4.2.7/libswscale/swscale_internal.h#L280) is an internal struct that shouldn't be handled. I'd say the "exported" struct is [here](https://github.com/FFmpeg/FFmpeg/blob/n4.4.1/libswscale/swscale.h#L122) and has no fields. I think the purpose of this is to avoid developers updating manually options (like we want to do).

Therefore I think there are 2 options :

1) use `sws_getContext` to set options directly, but I don't really like that since it's marked as deprecated
2) use [av_opt_set_dict](https://github.com/FFmpeg/FFmpeg/blob/n4.4.1/libavutil/opt.h#L483) to set options on the `SwsContext`. The `Dictionary` GO struct already exists therefore what you'd need to do is :
- add a `class.go` file with
```go
type Class struct {
  c *C.struct_AVClass
}

func (c Class) Name() string {
  return C.GoString(c.class_name)
}

type Classer interface {
    Class() Class
} 
```
- implement the `Classer` interface on `SwsContext`
- add an `options.go` file with
```go
func SetOptionsFromDictionary(o Classer, d *Dictionary) error {
  // TODO Call av_opt_set_dict
}
```
That way you could create a dictionary with "srcW=1280:srcH=720" for instance, and update `SwsContext` options with `SetOptionsFromDictionary`.

**Comment by asticode** [comment]
I think adding a `func(c *SwsContext) SetOptionsFromString(s string) error` would be nice too. It would create the dictionary and then call `SetOptionsFromDictionary`

**Comment by elwinar** [comment]
Hey. I'm sorry I haven't kept you updated, I've been a bit busy lately.

Short version is: I haven't had the time to work on this this past month due to personal matters (mainly moving to my new house, work ramping up, etc), so this got left out. I'll pick it up as soon as I'm able tho, I did not forget.
